### ISSUE TITLE
Cannot start application via docker compose and after running application via conda it gives the error message

### ISSUE THREAD

**Issue by masrooj** [hummingbot/backend-api#12]
1. 
![Screenshot 2024-04-30 at 17 11 48](https://github.com/hummingbot/backend-api/assets/7861852/7a3f67fa-beb7-4d08-9390-576d63170129)
I'm getting this error message via running conda 

 2. 
 
![Screenshot 2024-04-30 at 17 22 29](https://github.com/hummingbot/backend-api/assets/7861852/4f07eb47-e31f-4799-aec8-a7b29ad80f32)
I'm getting this issue when running via docker compose

**Comment by cardosofede** [comment]
we don't have the wheels for OSX64, are you using Intel Mac?
